export interface TrustedDomain {
  domain: string;
  category: TrustedDomainCategory;
  country: "VN" | "GLOBAL";
  trustScore: number;
  note?: string;
}
export type TrustedDomainCategory = "gov_vn" | "media_vn" | "bank_vn" | "gov_global" | "media_global" | "tech_global" | "edu_vn" | "health_vn" | "fintech_vn" | "ecom_vn" | "factcheck" | "security" | "telecom_vn";
export const TRUSTED_DOMAINS: TrustedDomain[] = [
{ domain: "chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cổng thông tin điện tử Chính phủ" },
{ domain: "mps.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Công an" },
{ domain: "mic.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Thông tin & Truyền thông" },
{ domain: "mof.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Tài chính" },
{ domain: "moet.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Giáo dục & Đào tạo" },
{ domain: "moh.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Y tế" },
{ domain: "molisa.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Lao động TBXH" },
{ domain: "mard.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Nông nghiệp & PTNT" },
{ domain: "mot.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Giao thông Vận tải" },
{ domain: "moc.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Xây dựng" },
{ domain: "mofa.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Ngoại giao" },
{ domain: "mpi.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Kế hoạch & Đầu tư" },
{ domain: "moit.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Công Thương" },
{ domain: "monre.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Tài nguyên & Môi trường" },
{ domain: "mcst.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Văn hóa Thể thao Du lịch" },
{ domain: "nacis.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cục An ninh mạng (Bộ Công an)" },
{ domain: "vneids.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hệ thống định danh điện tử VNeID" },
{ domain: "dichvucong.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cổng dịch vụ công quốc gia" },
{ domain: "gdt.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tổng cục Thuế" },
{ domain: "customs.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tổng cục Hải quan" },
{ domain: "bhxh.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bảo hiểm Xã hội Việt Nam" },
{ domain: "vnpt.gov.vn", category: "gov_vn", country: "VN", trustScore: 95, note: "VNPT - Tập đoàn BC-VT" },
{ domain: "sbv.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Ngân hàng Nhà nước Việt Nam" },
{ domain: "gdlegal.moj.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ Tư pháp" },
{ domain: "sggp.org.vn", category: "gov_vn", country: "VN", trustScore: 95, note: "Sài Gòn Giải Phóng" },
{ domain: "hanoitv.vn", category: "gov_vn", country: "VN", trustScore: 90, note: "Đài Hà Nội" },
{ domain: "hcmc.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "UBND TP.HCM" },
{ domain: "hanoi.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "UBND Thành phố Hà Nội" },
{ domain: "cand.com.vn", category: "gov_vn", country: "VN", trustScore: 95, note: "Báo Công an Nhân dân" },
{ domain: "vksndtc.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Viện Kiểm sát Nhân dân Tối cao" },
{ domain: "toaan.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tòa án Nhân dân Tối cao" },
{ domain: "dangcongsan.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đảng Cộng sản Việt Nam" },
{ domain: "mattran.org.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Mặt trận Tổ quốc Việt Nam" },
{ domain: "nld.com.vn", category: "media_vn", country: "VN", trustScore: 90, note: "Báo Người Lao Động" },
{ domain: "vnexpress.net", category: "media_vn", country: "VN", trustScore: 95, note: "VnExpress - Báo điện tử lớn nhất VN" },
{ domain: "tuoitre.vn", category: "media_vn", country: "VN", trustScore: 95, note: "Báo Tuổi Trẻ" },
{ domain: "thanhnien.vn", category: "media_vn", country: "VN", trustScore: 95, note: "Báo Thanh Niên" },
{ domain: "dantri.com.vn", category: "media_vn", country: "VN", trustScore: 90, note: "Dân Trí" },
{ domain: "vtv.vn", category: "media_vn", country: "VN", trustScore: 98, note: "Đài Truyền hình Việt Nam" },
{ domain: "vov.vn", category: "media_vn", country: "VN", trustScore: 98, note: "Đài Tiếng nói Việt Nam" },
{ domain: "nhandan.vn", category: "media_vn", country: "VN", trustScore: 98, note: "Báo Nhân Dân" },
{ domain: "baochinhphu.vn", category: "media_vn", country: "VN", trustScore: 100, note: "Báo Chính phủ" },
{ domain: "laodong.vn", category: "media_vn", country: "VN", trustScore: 88, note: "Báo Lao Động" },
{ domain: "vietnamnet.vn", category: "media_vn", country: "VN", trustScore: 88, note: "VietnamNet" },
{ domain: "tienphong.vn", category: "media_vn", country: "VN", trustScore: 88, note: "Báo Tiền Phong" },
{ domain: "zingnews.vn", category: "media_vn", country: "VN", trustScore: 85, note: "Zing News" },
{ domain: "baomoi.com", category: "media_vn", country: "VN", trustScore: 80, note: "Bao Mới - Tổng hợp" },
{ domain: "vtcnews.vn", category: "media_vn", country: "VN", trustScore: 85, note: "VTC News" },
{ domain: "soha.vn", category: "media_vn", country: "VN", trustScore: 80, note: "Soha News" },
{ domain: "anninhthudo.vn", category: "media_vn", country: "VN", trustScore: 88, note: "An Ninh Thủ Đô" },
{ domain: "phapluat.vn", category: "media_vn", country: "VN", trustScore: 88, note: "Pháp Luật TP.HCM" },
{ domain: "cafebiz.vn", category: "media_vn", country: "VN", trustScore: 85, note: "CafeBiz - Kinh doanh" },
{ domain: "cafef.vn", category: "media_vn", country: "VN", trustScore: 85, note: "CafeF - Tài chính" },
{ domain: "baodautu.vn", category: "media_vn", country: "VN", trustScore: 88, note: "Báo Đầu Tư" },
{ domain: "vneconomy.vn", category: "media_vn", country: "VN", trustScore: 90, note: "Vietnam Economy" },
{ domain: "baotintuc.vn", category: "media_vn", country: "VN", trustScore: 90, note: "Báo Tin Tức (TTXVN)" },
{ domain: "vnanet.vn", category: "media_vn", country: "VN", trustScore: 98, note: "Thông tấn xã Việt Nam" },
{ domain: "antv.gov.vn", category: "media_vn", country: "VN", trustScore: 98, note: "An ninh TV" },
{ domain: "quandoinhandan.vn", category: "media_vn", country: "VN", trustScore: 95, note: "Báo Quân đội Nhân dân" },
{ domain: "plo.vn", category: "media_vn", country: "VN", trustScore: 88, note: "Pháp Luật Online" },
{ domain: "congthuong.vn", category: "media_vn", country: "VN", trustScore: 88, note: "Tạp chí Công Thương" },
{ domain: "tapchitaichinh.vn", category: "media_vn", country: "VN", trustScore: 90, note: "Tạp chí Tài Chính" },
{ domain: "kiemtoan.vn", category: "media_vn", country: "VN", trustScore: 90, note: "Kiểm Toán Nhà Nước" },
{ domain: "dangkykinhdoanh.gov.vn", category: "gov_vn", country: "VN", trustScore: 100 },
{ domain: "vietcombank.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "Ngân hàng Vietcombank" },
{ domain: "vcb.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "VCB - Vietcombank domain phụ" },
{ domain: "mbbank.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "MB Bank" },
{ domain: "vpbank.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "VPBank" },
{ domain: "techcombank.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "Techcombank" },
{ domain: "agribank.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "Agribank" },
{ domain: "bidv.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "BIDV" },
{ domain: "vietinbank.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "VietinBank" },
{ domain: "hdbank.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "HDBank" },
{ domain: "acb.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "ACB" },
{ domain: "sacombank.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "Sacombank" },
{ domain: "tpbank.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "TPBank" },
{ domain: "vib.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "VIB" },
{ domain: "msb.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "MSB" },
{ domain: "seabank.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "SeABank" },
{ domain: "ocb.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "OCB" },
{ domain: "ncb.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "NCB" },
{ domain: "bvb.com.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "BaoViet Bank" },
{ domain: "scb.com.vn", category: "bank_vn", country: "VN", trustScore: 90, note: "SCB" },
{ domain: "abbank.vn", category: "bank_vn", country: "VN", trustScore: 100, note: "ABBank" },
{ domain: "momo.vn", category: "fintech_vn", country: "VN", trustScore: 95, note: "Ví MoMo" },
{ domain: "zalopay.vn", category: "fintech_vn", country: "VN", trustScore: 95, note: "ZaloPay" },
{ domain: "vnpay.vn", category: "fintech_vn", country: "VN", trustScore: 95, note: "VNPAY" },
{ domain: "viettel.com.vn", category: "telecom_vn", country: "VN", trustScore: 95, note: "Viettel" },
{ domain: "viettelmoney.vn", category: "fintech_vn", country: "VN", trustScore: 95, note: "Viettel Money" },
{ domain: "shopeepay.vn", category: "fintech_vn", country: "VN", trustScore: 92, note: "ShopeePay" },
{ domain: "grab.com", category: "fintech_vn", country: "GLOBAL", trustScore: 90, note: "Grab" },
{ domain: "mservice.com.vn", category: "fintech_vn", country: "VN", trustScore: 95, note: "M_Service (MoMo parent)" },
{ domain: "payoo.vn", category: "fintech_vn", country: "VN", trustScore: 90, note: "Payoo" },
{ domain: "shopee.vn", category: "ecom_vn", country: "VN", trustScore: 90, note: "Shopee Việt Nam" },
{ domain: "lazada.vn", category: "ecom_vn", country: "VN", trustScore: 90, note: "Lazada Việt Nam" },
{ domain: "tiki.vn", category: "ecom_vn", country: "VN", trustScore: 90, note: "Tiki" },
{ domain: "sendo.vn", category: "ecom_vn", country: "VN", trustScore: 85, note: "Sendo" },
{ domain: "thegioididong.com", category: "ecom_vn", country: "VN", trustScore: 92, note: "Thế Giới Di Động" },
{ domain: "cellphones.com.vn", category: "ecom_vn", country: "VN", trustScore: 90, note: "CellphoneS" },
{ domain: "fptshop.com.vn", category: "ecom_vn", country: "VN", trustScore: 90, note: "FPT Shop" },
{ domain: "dienmayxanh.com", category: "ecom_vn", country: "VN", trustScore: 92, note: "Điện Máy Xanh" },
{ domain: "mobifone.vn", category: "telecom_vn", country: "VN", trustScore: 95, note: "MobiFone" },
{ domain: "vinaphone.vn", category: "telecom_vn", country: "VN", trustScore: 95, note: "VinaPhone" },
{ domain: "vietnamobile.com.vn", category: "telecom_vn", country: "VN", trustScore: 90, note: "Vietnamobile" },
{ domain: "fpt.vn", category: "telecom_vn", country: "VN", trustScore: 92, note: "FPT Telecom" },
{ domain: "vnpt.vn", category: "telecom_vn", country: "VN", trustScore: 95, note: "VNPT" },
{ domain: "vietpost.vn", category: "telecom_vn", country: "VN", trustScore: 90, note: "Viettel Post" },
{ domain: "hust.edu.vn", category: "edu_vn", country: "VN", trustScore: 95, note: "ĐH Bách Khoa Hà Nội" },
{ domain: "vnu.edu.vn", category: "edu_vn", country: "VN", trustScore: 95, note: "ĐH Quốc gia Hà Nội" },
{ domain: "vnuhcm.edu.vn", category: "edu_vn", country: "VN", trustScore: 95, note: "ĐH Quốc gia TP.HCM" },
{ domain: "hcmus.edu.vn", category: "edu_vn", country: "VN", trustScore: 95, note: "ĐH Khoa học Tự nhiên" },
{ domain: "hcmut.edu.vn", category: "edu_vn", country: "VN", trustScore: 95, note: "ĐH Bách Khoa TP.HCM" },
{ domain: "ueh.edu.vn", category: "edu_vn", country: "VN", trustScore: 95, note: "ĐH Kinh tế TP.HCM" },
{ domain: "neu.edu.vn", category: "edu_vn", country: "VN", trustScore: 95, note: "ĐH Kinh tế Quốc dân" },
{ domain: "ftu.edu.vn", category: "edu_vn", country: "VN", trustScore: 95, note: "ĐH Ngoại Thương" },
{ domain: "vinmec.com", category: "health_vn", country: "VN", trustScore: 95, note: "Vinmec" },
{ domain: "bachmai.gov.vn", category: "health_vn", country: "VN", trustScore: 100, note: "BV Bạch Mai" },
{ domain: "choyray.com.vn", category: "health_vn", country: "VN", trustScore: 100, note: "BV Chợ Rẫy" },
{ domain: "108-ictu.edu.vn", category: "health_vn", country: "VN", trustScore: 100, note: "BV 108" },
{ domain: "medlatec.vn", category: "health_vn", country: "VN", trustScore: 90, note: "MEDLATEC" },
{ domain: "hellobacsi.com", category: "health_vn", country: "VN", trustScore: 85, note: "Hello Bác Sĩ" },
{ domain: "thuocbietduoc.com.vn", category: "health_vn", country: "VN", trustScore: 88, note: "Thuốc Biệt Dược" },
{ domain: "who.int", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Tổ chức Y tế Thế giới" },
{ domain: "un.org", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Liên Hợp Quốc" },
{ domain: "worldbank.org", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Ngân hàng Thế giới" },
{ domain: "imf.org", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "IMF" },
{ domain: "unicef.org", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "UNICEF" },
{ domain: "undp.org", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "UNDP" },
{ domain: "asean.org", category: "gov_global", country: "GLOBAL", trustScore: 98, note: "ASEAN" },
{ domain: "interpol.int", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "INTERPOL" },
{ domain: "gov.uk", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Chính phủ Anh" },
{ domain: "whitehouse.gov", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Nhà Trắng Mỹ" },
{ domain: "reuters.com", category: "media_global", country: "GLOBAL", trustScore: 98, note: "Reuters" },
{ domain: "apnews.com", category: "media_global", country: "GLOBAL", trustScore: 98, note: "AP News" },
{ domain: "afp.com", category: "media_global", country: "GLOBAL", trustScore: 98, note: "AFP" },
{ domain: "bbc.com", category: "media_global", country: "GLOBAL", trustScore: 95, note: "BBC" },
{ domain: "cnn.com", category: "media_global", country: "GLOBAL", trustScore: 90, note: "CNN" },
{ domain: "nytimes.com", category: "media_global", country: "GLOBAL", trustScore: 95, note: "New York Times" },
{ domain: "theguardian.com", category: "media_global", country: "GLOBAL", trustScore: 92, note: "The Guardian" },
{ domain: "wsj.com", category: "media_global", country: "GLOBAL", trustScore: 95, note: "Wall Street Journal" },
{ domain: "ft.com", category: "media_global", country: "GLOBAL", trustScore: 95, note: "Financial Times" },
{ domain: "bloomberg.com", category: "media_global", country: "GLOBAL", trustScore: 95, note: "Bloomberg" },
{ domain: "economist.com", category: "media_global", country: "GLOBAL", trustScore: 95, note: "The Economist" },
{ domain: "voanews.com", category: "media_global", country: "GLOBAL", trustScore: 90, note: "VOA" },
{ domain: "rfa.org", category: "media_global", country: "GLOBAL", trustScore: 85, note: "RFA" },
{ domain: "nhk.or.jp", category: "media_global", country: "GLOBAL", trustScore: 95, note: "NHK" },
{ domain: "dw.com", category: "media_global", country: "GLOBAL", trustScore: 92, note: "Deutsche Welle" },
{ domain: "france24.com", category: "media_global", country: "GLOBAL", trustScore: 92, note: "France 24" },
{ domain: "factcheck.org", category: "factcheck", country: "GLOBAL", trustScore: 98, note: "FactCheck.org" },
{ domain: "snopes.com", category: "factcheck", country: "GLOBAL", trustScore: 92, note: "Snopes" },
{ domain: "politifact.com", category: "factcheck", country: "GLOBAL", trustScore: 92, note: "PolitiFact" },
{ domain: "fullfact.org", category: "factcheck", country: "GLOBAL", trustScore: 92, note: "Full Fact" },
{ domain: "factcheckvn.vn", category: "factcheck", country: "VN", trustScore: 95, note: "Fact-check Việt Nam" },
{ domain: "tingia.gov.vn", category: "factcheck", country: "VN", trustScore: 100, note: "Cổng kiểm tin Chính phủ" },
{ domain: "google.com/factcheck", category: "factcheck", country: "GLOBAL", trustScore: 98, note: "Google Fact Check" },
{ domain: "ifcncodeofprinciples.poynter.org", category: "factcheck", country: "GLOBAL", trustScore: 98 },
{ domain: "google.com", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "Google" },
{ domain: "microsoft.com", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "Microsoft" },
{ domain: "apple.com", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "Apple" },
{ domain: "meta.com", category: "tech_global", country: "GLOBAL", trustScore: 85, note: "Meta (Facebook)" },
{ domain: "facebook.com", category: "tech_global", country: "GLOBAL", trustScore: 80, note: "Facebook" },
{ domain: "twitter.com", category: "tech_global", country: "GLOBAL", trustScore: 75, note: "Twitter/X" },
{ domain: "x.com", category: "tech_global", country: "GLOBAL", trustScore: 75, note: "X (Twitter)" },
{ domain: "youtube.com", category: "tech_global", country: "GLOBAL", trustScore: 80, note: "YouTube" },
{ domain: "amazon.com", category: "tech_global", country: "GLOBAL", trustScore: 90, note: "Amazon" },
{ domain: "zalo.me", category: "tech_global", country: "VN", trustScore: 88, note: "Zalo" },
{ domain: "tiktok.com", category: "tech_global", country: "GLOBAL", trustScore: 72, note: "TikTok" },
{ domain: "virustotal.com", category: "security", country: "GLOBAL", trustScore: 98, note: "VirusTotal" },
{ domain: "phishtank.com", category: "security", country: "GLOBAL", trustScore: 95, note: "PhishTank" },
{ domain: "openphish.com", category: "security", country: "GLOBAL", trustScore: 95, note: "OpenPhish" },
{ domain: "haveibeenpwned.com", category: "security", country: "GLOBAL", trustScore: 95, note: "Have I Been Pwned" },
{ domain: "abuseipdb.com", category: "security", country: "GLOBAL", trustScore: 90, note: "AbuseIPDB" },
{ domain: "malwarebytes.com", category: "security", country: "GLOBAL", trustScore: 92, note: "Malwarebytes" },
{ domain: "kaspersky.com", category: "security", country: "GLOBAL", trustScore: 88, note: "Kaspersky" },
{ domain: "mcafee.com", category: "security", country: "GLOBAL", trustScore: 88, note: "McAfee" },
{ domain: "trendmicro.com", category: "security", country: "GLOBAL", trustScore: 90, note: "Trend Micro" },
{ domain: "eset.com", category: "security", country: "GLOBAL", trustScore: 90, note: "ESET" },
{ domain: "norton.com", category: "security", country: "GLOBAL", trustScore: 88, note: "Norton" },
{ domain: "avg.com", category: "security", country: "GLOBAL", trustScore: 85, note: "AVG" },
{ domain: "avast.com", category: "security", country: "GLOBAL", trustScore: 85, note: "Avast" },
{ domain: "bitdefender.com", category: "security", country: "GLOBAL", trustScore: 90, note: "Bitdefender" },
{ domain: "sophos.com", category: "security", country: "GLOBAL", trustScore: 88, note: "Sophos" },
{ domain: "cyren.com", category: "security", country: "GLOBAL", trustScore: 85, note: "Cyren" },
{ domain: "forcepoint.com", category: "security", country: "GLOBAL", trustScore: 88, note: "Forcepoint" },
{ domain: "paloaltonetworks.com", category: "security", country: "GLOBAL", trustScore: 92, note: "Palo Alto Networks" },
{ domain: "fortinet.com", category: "security", country: "GLOBAL", trustScore: 90, note: "Fortinet" },
{ domain: "checkpoint.com", category: "security", country: "GLOBAL", trustScore: 90, note: "Check Point" },
{ domain: "crowdstrike.com", category: "security", country: "GLOBAL", trustScore: 92, note: "CrowdStrike" },
{ domain: "sentinelone.com", category: "security", country: "GLOBAL", trustScore: 88, note: "SentinelOne" },
{ domain: "snyk.io", category: "security", country: "GLOBAL", trustScore: 90, note: "Snyk" },
{ domain: "github.com", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "GitHub" },
{ domain: "gitlab.com", category: "tech_global", country: "GLOBAL", trustScore: 92, note: "GitLab" },
{ domain: "stackoverflow.com", category: "tech_global", country: "GLOBAL", trustScore: 90, note: "Stack Overflow" },
{ domain: "npmjs.com", category: "tech_global", country: "GLOBAL", trustScore: 88, note: "npm" },
{ domain: "pypi.org", category: "tech_global", country: "GLOBAL", trustScore: 90, note: "PyPI" },
{ domain: "docker.com", category: "tech_global", country: "GLOBAL", trustScore: 90, note: "Docker" },
{ domain: "kubernetes.io", category: "tech_global", country: "GLOBAL", trustScore: 92, note: "Kubernetes" },
{ domain: "aws.amazon.com", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "AWS" },
{ domain: "azure.microsoft.com", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "Azure" },
{ domain: "cloud.google.com", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "Google Cloud" },
{ domain: "vercel.com", category: "tech_global", country: "GLOBAL", trustScore: 90, note: "Vercel" },
{ domain: "netlify.com", category: "tech_global", country: "GLOBAL", trustScore: 88, note: "Netlify" },
{ domain: "heroku.com", category: "tech_global", country: "GLOBAL", trustScore: 88, note: "Heroku" },
{ domain: "digitalocean.com", category: "tech_global", country: "GLOBAL", trustScore: 88, note: "DigitalOcean" },
{ domain: "linode.com", category: "tech_global", country: "GLOBAL", trustScore: 88, note: "Linode" },
{ domain: "vultr.com", category: "tech_global", country: "GLOBAL", trustScore: 85, note: "Vultr" },
{ domain: "cloudflare.com", category: "tech_global", country: "GLOBAL", trustScore: 92, note: "Cloudflare" },
{ domain: "akamai.com", category: "tech_global", country: "GLOBAL", trustScore: 90, note: "Akamai" },
{ domain: "fastly.com", category: "tech_global", country: "GLOBAL", trustScore: 88, note: "Fastly" },
{ domain: "linkedin.com", category: "tech_global", country: "GLOBAL", trustScore: 85, note: "LinkedIn" },
{ domain: "instagram.com", category: "tech_global", country: "GLOBAL", trustScore: 80, note: "Instagram" },
{ domain: "pinterest.com", category: "tech_global", country: "GLOBAL", trustScore: 78, note: "Pinterest" },
{ domain: "reddit.com", category: "tech_global", country: "GLOBAL", trustScore: 80, note: "Reddit" },
{ domain: "quora.com", category: "tech_global", country: "GLOBAL", trustScore: 78, note: "Quora" },
{ domain: "medium.com", category: "tech_global", country: "GLOBAL", trustScore: 82, note: "Medium" },
{ domain: "substack.com", category: "tech_global", country: "GLOBAL", trustScore: 80, note: "Substack" },
{ domain: "notion.so", category: "tech_global", country: "GLOBAL", trustScore: 88, note: "Notion" },
{ domain: "figma.com", category: "tech_global", country: "GLOBAL", trustScore: 90, note: "Figma" },
{ domain: "canva.com", category: "tech_global", country: "GLOBAL", trustScore: 88, note: "Canva" },
{ domain: "grammarly.com", category: "tech_global", country: "GLOBAL", trustScore: 85, note: "Grammarly" },
{ domain: "duolingo.com", category: "tech_global", country: "GLOBAL", trustScore: 85, note: "Duolingo" },
{ domain: "coursera.org", category: "edu_vn", country: "GLOBAL", trustScore: 92, note: "Coursera" },
{ domain: "edx.org", category: "edu_vn", country: "GLOBAL", trustScore: 90, note: "edX" },
{ domain: "khanacademy.org", category: "edu_vn", country: "GLOBAL", trustScore: 92, note: "Khan Academy" },
{ domain: "udemy.com", category: "edu_vn", country: "GLOBAL", trustScore: 85, note: "Udemy" },
{ domain: "pluralsight.com", category: "edu_vn", country: "GLOBAL", trustScore: 85, note: "Pluralsight" },
{ domain: "skillshare.com", category: "edu_vn", country: "GLOBAL", trustScore: 82, note: "Skillshare" },
{ domain: "codecademy.com", category: "edu_vn", country: "GLOBAL", trustScore: 85, note: "Codecademy" },
{ domain: "freecodecamp.org", category: "edu_vn", country: "GLOBAL", trustScore: 88, note: "freeCodeCamp" },
{ domain: "wikipedia.org", category: "media_global", country: "GLOBAL", trustScore: 85, note: "Wikipedia" },
{ domain: "wikimedia.org", category: "media_global", country: "GLOBAL", trustScore: 88, note: "Wikimedia" },
{ domain: "britannica.com", category: "media_global", country: "GLOBAL", trustScore: 92, note: "Encyclopedia Britannica" },
{ domain: "scholar.google.com", category: "media_global", country: "GLOBAL", trustScore: 90, note: "Google Scholar" },
{ domain: "arxiv.org", category: "media_global", country: "GLOBAL", trustScore: 92, note: "arXiv" },
{ domain: "pubmed.ncbi.nlm.nih.gov", category: "media_global", country: "GLOBAL", trustScore: 95, note: "PubMed" },
{ domain: "nasa.gov", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "NASA" },
{ domain: "nih.gov", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "NIH" },
{ domain: "cdc.gov", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "CDC" },
{ domain: "fda.gov", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "FDA" },
{ domain: "europa.eu", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "European Union" },
{ domain: "parliament.uk", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "UK Parliament" },
{ domain: "bundesregierung.de", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "German Government" },
{ domain: "gouv.fr", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "French Government" },
{ domain: "japan.go.jp", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Japanese Government" },
{ domain: "gov.sg", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Singapore Government" },
{ domain: "gov.au", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Australian Government" },
{ domain: "canada.ca", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Canadian Government" },
{ domain: "gob.mx", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Mexican Government" },
{ domain: "gob.br", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Brazilian Government" },
{ domain: "india.gov.in", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Indian Government" },
{ domain: "gov.kr", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "Korean Government" },
{ domain: "gov.tw", category: "gov_global", country: "GLOBAL", trustScore: 95, note: "Taiwan Government" },
{ domain: "gov.my", category: "gov_global", country: "GLOBAL", trustScore: 95, note: "Malaysian Government" },
{ domain: "phl.gov.ph", category: "gov_global", country: "GLOBAL", trustScore: 90, note: "Philippine Government" },
{ domain: "thai.go.th", category: "gov_global", country: "GLOBAL", trustScore: 90, note: "Thai Government" },
{ domain: "kemendagri.go.id", category: "gov_global", country: "GLOBAL", trustScore: 90, note: "Indonesian Government" },
{ domain: "who.int", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "WHO" },
{ domain: "imo.org", category: "gov_global", country: "GLOBAL", trustScore: 95, note: "IMO" },
{ domain: "icao.int", category: "gov_global", country: "GLOBAL", trustScore: 95, note: "ICAO" },
{ domain: "itu.int", category: "gov_global", country: "GLOBAL", trustScore: 95, note: "ITU" },
{ domain: "wto.org", category: "gov_global", country: "GLOBAL", trustScore: 98, note: "WTO" },
{ domain: "oecd.org", category: "gov_global", country: "GLOBAL", trustScore: 98, note: "OECD" },
{ domain: "iaea.org", category: "gov_global", country: "GLOBAL", trustScore: 100, note: "IAEA" },
{ domain: "copolco.oecd.org", category: "gov_global", country: "GLOBAL", trustScore: 95, note: "OECD Consumer Policy" },
{ domain: "digitalocean.com", category: "tech_global", country: "GLOBAL", trustScore: 88, note: "DigitalOcean" },
{ domain: "shopify.com", category: "ecom_vn", country: "GLOBAL", trustScore: 90, note: "Shopify" },
{ domain: "ebay.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "eBay" },
{ domain: "walmart.com", category: "ecom_vn", country: "GLOBAL", trustScore: 88, note: "Walmart" },
{ domain: "target.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "Target" },
{ domain: "bestbuy.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "Best Buy" },
{ domain: "costco.com", category: "ecom_vn", country: "GLOBAL", trustScore: 88, note: "Costco" },
{ domain: "homedepot.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "Home Depot" },
{ domain: "lowes.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "Lowe's" },
{ domain: "ikea.com", category: "ecom_vn", country: "GLOBAL", trustScore: 88, note: "IKEA" },
{ domain: "zara.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "Zara" },
{ domain: "hm.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "H&M" },
{ domain: "nike.com", category: "ecom_vn", country: "GLOBAL", trustScore: 88, note: "Nike" },
{ domain: "adidas.com", category: "ecom_vn", country: "GLOBAL", trustScore: 88, note: "Adidas" },
{ domain: "puma.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "Puma" },
{ domain: "newbalance.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "New Balance" },
{ domain: "underarmour.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "Under Armour" },
{ domain: "lego.com", category: "ecom_vn", country: "GLOBAL", trustScore: 88, note: "LEGO" },
{ domain: "hasbro.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "Hasbro" },
{ domain: "mattel.com", category: "ecom_vn", country: "GLOBAL", trustScore: 85, note: "Mattel" },
{ domain: "disney.com", category: "media_global", country: "GLOBAL", trustScore: 88, note: "Disney" },
{ domain: "netflix.com", category: "media_global", country: "GLOBAL", trustScore: 85, note: "Netflix" },
{ domain: "spotify.com", category: "media_global", country: "GLOBAL", trustScore: 85, note: "Spotify" },
{ domain: "hulu.com", category: "media_global", country: "GLOBAL", trustScore: 82, note: "Hulu" },
{ domain: "hbomax.com", category: "media_global", country: "GLOBAL", trustScore: 82, note: "HBO Max" },
{ domain: "peacocktv.com", category: "media_global", country: "GLOBAL", trustScore: 80, note: "Peacock" },
{ domain: "paramountplus.com", category: "media_global", country: "GLOBAL", trustScore: 80, note: "Paramount+" },
{ domain: "apple.com/tv", category: "media_global", country: "GLOBAL", trustScore: 85, note: "Apple TV+" },
{ domain: "primevideo.com", category: "media_global", country: "GLOBAL", trustScore: 85, note: "Amazon Prime Video" },
{ domain: "crunchyroll.com", category: "media_global", country: "GLOBAL", trustScore: 82, note: "Crunchyroll" },
{ domain: "funimation.com", category: "media_global", country: "GLOBAL", trustScore: 80, note: "Funimation" },
{ domain: "viki.com", category: "media_global", country: "GLOBAL", trustScore: 80, note: "Viki" },
{ domain: "iheart.com", category: "media_global", country: "GLOBAL", trustScore: 82, note: "iHeartRadio" },
{ domain: "tunein.com", category: "media_global", country: "GLOBAL", trustScore: 80, note: "TuneIn" },
{ domain: "soundcloud.com", category: "media_global", country: "GLOBAL", trustScore: 78, note: "SoundCloud" },
{ domain: "bandcamp.com", category: "media_global", country: "GLOBAL", trustScore: 80, note: "Bandcamp" },
{ domain: "mixcloud.com", category: "media_global", country: "GLOBAL", trustScore: 78, note: "Mixcloud" },
{ domain: "deezer.com", category: "media_global", country: "GLOBAL", trustScore: 82, note: "Deezer" },
{ domain: "tidal.com", category: "media_global", country: "GLOBAL", trustScore: 80, note: "Tidal" },
{ domain: "pandora.com", category: "media_global", country: "GLOBAL", trustScore: 80, note: "Pandora" },
{ domain: "last.fm", category: "media_global", country: "GLOBAL", trustScore: 78, note: "Last.fm" },
{ domain: "genius.com", category: "media_global", country: "GLOBAL", trustScore: 80, note: "Genius" },
{ domain: "musixmatch.com", category: "media_global", country: "GLOBAL", trustScore: 78, note: "Musixmatch" },
{ domain: "shazam.com", category: "media_global", country: "GLOBAL", trustScore: 82, note: "Shazam" },
{ domain: "twitch.tv", category: "media_global", country: "GLOBAL", trustScore: 80, note: "Twitch" },
{ domain: "vimeo.com", category: "media_global", country: "GLOBAL", trustScore: 82, note: "Vimeo" },
{ domain: "dailymotion.com", category: "media_global", country: "GLOBAL", trustScore: 78, note: "Dailymotion" },
{ domain: "rumble.com", category: "media_global", country: "GLOBAL", trustScore: 75, note: "Rumble" },
{ domain: "odysee.com", category: "media_global", country: "GLOBAL", trustScore: 72, note: "Odysee" },
{ domain: "bitchute.com", category: "media_global", country: "GLOBAL", trustScore: 65, note: "Bitchute" },
{ domain: "gab.com", category: "media_global", country: "GLOBAL", trustScore: 55, note: "Gab" },
{ domain: " parler.com", category: "media_global", country: "GLOBAL", trustScore: 55, note: "Parler" },
{ domain: "gettr.com", category: "media_global", country: "GLOBAL", trustScore: 60, note: "GETTR" },
{ domain: "truthsocial.com", category: "media_global", country: "GLOBAL", trustScore: 60, note: "Truth Social" },
{ domain: "mewe.com", category: "media_global", country: "GLOBAL", trustScore: 65, note: "MeWe" },
{ domain: " Minds.com", category: "media_global", country: "GLOBAL", trustScore: 60, note: "Minds" },
{ domain: "bsky.app", category: "media_global", country: "GLOBAL", trustScore: 72, note: "Bluesky" },
{ domain: "threads.net", category: "media_global", country: "GLOBAL", trustScore: 75, note: "Threads" },
{ domain: "mastodon.social", category: "media_global", country: "GLOBAL", trustScore: 75, note: "Mastodon" },
{ domain: "lemmy.world", category: "media_global", country: "GLOBAL", trustScore: 70, note: "Lemmy" },
{ domain: "kbin.social", category: "media_global", country: "GLOBAL", trustScore: 68, note: "Kbin" },
{ domain: "diasp.org", category: "media_global", country: "GLOBAL", trustScore: 65, note: "Diaspora" },
{ domain: "friendica.com", category: "media_global", country: "GLOBAL", trustScore: 65, note: "Friendica" },
{ domain: "hubzilla.com", category: "media_global", country: "GLOBAL", trustScore: 65, note: "Hubzilla" },
{ domain: "pleroma.site", category: "media_global", country: "GLOBAL", trustScore: 65, note: "Pleroma" },
{ domain: "akkoma.social", category: "media_global", country: "GLOBAL", trustScore: 65, note: "Akkoma" },
{ domain: "firefish.social", category: "media_global", country: "GLOBAL", trustScore: 68, note: "Firefish" },
{ domain: "calckey.social", category: "media_global", country: "GLOBAL", trustScore: 68, note: "Calckey" },
{ domain: "misskey.social", category: "media_global", country: "GLOBAL", trustScore: 68, note: "Misskey" },
{ domain: "keybase.io", category: "security", country: "GLOBAL", trustScore: 85, note: "Keybase" },
{ domain: "1password.com", category: "security", country: "GLOBAL", trustScore: 90, note: "1Password" },
{ domain: "bitwarden.com", category: "security", country: "GLOBAL", trustScore: 88, note: "Bitwarden" },
{ domain: "dashlane.com", category: "security", country: "GLOBAL", trustScore: 85, note: "Dashlane" },
{ domain: "lastpass.com", category: "security", country: "GLOBAL", trustScore: 80, note: "LastPass" },
{ domain: "proton.me", category: "security", country: "GLOBAL", trustScore: 90, note: "Proton" },
{ domain: "protonmail.com", category: "security", country: "GLOBAL", trustScore: 90, note: "ProtonMail" },
{ domain: "protonvpn.com", category: "security", country: "GLOBAL", trustScore: 88, note: "ProtonVPN" },
{ domain: "tutanota.com", category: "security", country: "GLOBAL", trustScore: 85, note: "Tutanota" },
{ domain: "mullvad.net", category: "security", country: "GLOBAL", trustScore: 85, note: "Mullvad" },
{ domain: "expressvpn.com", category: "security", country: "GLOBAL", trustScore: 82, note: "ExpressVPN" },
{ domain: "nordvpn.com", category: "security", country: "GLOBAL", trustScore: 82, note: "NordVPN" },
{ domain: "surfshark.com", category: "security", country: "GLOBAL", trustScore: 80, note: "Surfshark" },
{ domain: "cyberghostvpn.com", category: "security", country: "GLOBAL", trustScore: 78, note: "CyberGhost" },
{ domain: "privateinternetaccess.com", category: "security", country: "GLOBAL", trustScore: 80, note: "PIA" },
{ domain: "ivpn.net", category: "security", country: "GLOBAL", trustScore: 82, note: "IVPN" },
{ domain: "windscribe.com", category: "security", country: "GLOBAL", trustScore: 78, note: "Windscribe" },
{ domain: "hidemy.name", category: "security", country: "GLOBAL", trustScore: 75, note: "HideMy.name" },
{ domain: "vpnunlimited.com", category: "security", country: "GLOBAL", trustScore: 75, note: "VPN Unlimited" },
{ domain: "hideman.net", category: "security", country: "GLOBAL", trustScore: 72, note: "HideMan" },
{ domain: "tunnelbear.com", category: "security", country: "GLOBAL", trustScore: 78, note: "TunnelBear" },
{ domain: "hotspotshield.com", category: "security", country: "GLOBAL", trustScore: 75, note: "Hotspot Shield" },
{ domain: "zenmate.com", category: "security", country: "GLOBAL", trustScore: 72, note: "ZenMate" },
{ domain: "purevpn.com", category: "security", country: "GLOBAL", trustScore: 75, note: "PureVPN" },
{ domain: "ipvanish.com", category: "security", country: "GLOBAL", trustScore: 75, note: "IPVanish" },
{ domain: "vyprvpn.com", category: "security", country: "GLOBAL", trustScore: 78, note: "VyprVPN" },
{ domain: "astrill.com", category: "security", country: "GLOBAL", trustScore: 78, note: "Astrill" },
{ domain: "getlantern.org", category: "security", country: "GLOBAL", trustScore: 75, note: "Lantern" },
{ domain: "psiphon.ca", category: "security", country: "GLOBAL", trustScore: 78, note: "Psiphon" },
{ domain: "torproject.org", category: "security", country: "GLOBAL", trustScore: 90, note: "Tor Project" },
{ domain: "signal.org", category: "security", country: "GLOBAL", trustScore: 92, note: "Signal" },
{ domain: "whatsapp.com", category: "tech_global", country: "GLOBAL", trustScore: 80, note: "WhatsApp" },
{ domain: "telegram.org", category: "tech_global", country: "GLOBAL", trustScore: 78, note: "Telegram" },
{ domain: "line.me", category: "tech_global", country: "GLOBAL", trustScore: 82, note: "LINE" },
{ domain: "viber.com", category: "tech_global", country: "GLOBAL", trustScore: 78, note: "Viber" },
{ domain: "wechat.com", category: "tech_global", country: "GLOBAL", trustScore: 75, note: "WeChat" },
{ domain: "qq.com", category: "tech_global", country: "GLOBAL", trustScore: 72, note: "QQ" },
{ domain: "weibo.com", category: "tech_global", country: "GLOBAL", trustScore: 72, note: "Weibo" },
{ domain: "twitter.com", category: "tech_global", country: "GLOBAL", trustScore: 75, note: "Twitter" },
{ domain: "x.com", category: "tech_global", country: "GLOBAL", trustScore: 75, note: "X" },
{ domain: "snapchat.com", category: "tech_global", country: "GLOBAL", trustScore: 78, note: "Snapchat" },
{ domain: "discord.com", category: "tech_global", country: "GLOBAL", trustScore: 80, note: "Discord" },
{ domain: "slack.com", category: "tech_global", country: "GLOBAL", trustScore: 85, note: "Slack" },
{ domain: "zoom.us", category: "tech_global", country: "GLOBAL", trustScore: 82, note: "Zoom" },
{ domain: "teams.microsoft.com", category: "tech_global", country: "GLOBAL", trustScore: 88, note: "Microsoft Teams" },
{ domain: "meet.google.com", category: "tech_global", country: "GLOBAL", trustScore: 88, note: "Google Meet" },
{ domain: "skype.com", category: "tech_global", country: "GLOBAL", trustScore: 80, note: "Skype" },
{ domain: "webex.com", category: "tech_global", country: "GLOBAL", trustScore: 82, note: "Webex" },
{ domain: "gotomeeting.com", category: "tech_global", country: "GLOBAL", trustScore: 80, note: "GoTo Meeting" },
{ domain: "ringcentral.com", category: "tech_global", country: "GLOBAL", trustScore: 82, note: "RingCentral" },
{ domain: "dialpad.com", category: "tech_global", country: "GLOBAL", trustScore: 78, note: "Dialpad" },
{ domain: "firewalls.com", category: "security", country: "GLOBAL", trustScore: 80, note: "Firewalls.com" },
{ domain: "sans.org", category: "security", country: "GLOBAL", trustScore: 92, note: "SANS Institute" },
{ domain: "owasp.org", category: "security", country: "GLOBAL", trustScore: 90, note: "OWASP" },
{ domain: "cve.org", category: "security", country: "GLOBAL", trustScore: 95, note: "CVE" },
{ domain: "nist.gov", category: "security", country: "GLOBAL", trustScore: 100, note: "NIST" },
{ domain: "cisa.gov", category: "security", country: "GLOBAL", trustScore: 100, note: "CISA" },
{ domain: "us-cert.gov", category: "security", country: "GLOBAL", trustScore: 100, note: "US-CERT" },
{ domain: "enisa.europa.eu", category: "security", country: "GLOBAL", trustScore: 98, note: "ENISA" },
{ domain: "ncsc.gov.uk", category: "security", country: "GLOBAL", trustScore: 98, note: "NCSC UK" },
{ domain: "cert.org", category: "security", country: "GLOBAL", trustScore: 95, note: "CERT" },
{ domain: "certs.org", category: "security", country: "GLOBAL", trustScore: 92, note: "CERTS" },
{ domain: "rfc-editor.org", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "RFC Editor" },
{ domain: "ietf.org", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "IETF" },
{ domain: "w3.org", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "W3C" },
{ domain: "ecma-international.org", category: "tech_global", country: "GLOBAL", trustScore: 92, note: "ECMA" },
{ domain: "iso.org", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "ISO" },
{ domain: "ieee.org", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "IEEE" },
{ domain: "acm.org", category: "tech_global", country: "GLOBAL", trustScore: 95, note: "ACM" },
{ domain: "springer.com", category: "media_global", country: "GLOBAL", trustScore: 90, note: "Springer" },
{ domain: "sciencedirect.com", category: "media_global", country: "GLOBAL", trustScore: 90, note: "ScienceDirect" },
{ domain: "nature.com", category: "media_global", country: "GLOBAL", trustScore: 95, note: "Nature" },
{ domain: "science.org", category: "media_global", country: "GLOBAL", trustScore: 95, note: "Science" },
{ domain: "cell.com", category: "media_global", country: "GLOBAL", trustScore: 92, note: "Cell Press" },
{ domain: "thelancet.com", category: "media_global", country: "GLOBAL", trustScore: 95, note: "The Lancet" },
{ domain: "bmj.com", category: "media_global", country: "GLOBAL", trustScore: 92, note: "BMJ" },
{ domain: "nejm.org", category: "media_global", country: "GLOBAL", trustScore: 95, note: "NEJM" },
{ domain: "jamanetwork.com", category: "media_global", country: "GLOBAL", trustScore: 92, note: "JAMA" },
{ domain: "academic.oup.com", category: "media_global", country: "GLOBAL", trustScore: 90, note: "Oxford Academic" },
{ domain: "tandfonline.com", category: "media_global", country: "GLOBAL", trustScore: 88, note: "Taylor & Francis" },
{ domain: "wiley.com", category: "media_global", country: "GLOBAL", trustScore: 90, note: "Wiley" },
{ domain: "mdpi.com", category: "media_global", country: "GLOBAL", trustScore: 85, note: "MDPI" },
{ domain: "frontiersin.org", category: "media_global", country: "GLOBAL", trustScore: 85, note: "Frontiers" },
{ domain: "plos.org", category: "media_global", country: "GLOBAL", trustScore: 88, note: "PLOS" },
{ domain: "peerj.com", category: "media_global", country: "GLOBAL", trustScore: 82, note: "PeerJ" },
{ domain: "f1000research.com", category: "media_global", country: "GLOBAL", trustScore: 82, note: "F1000Research" },
{ domain: "ssrn.com", category: "media_global", country: "GLOBAL", trustScore: 85, note: "SSRN" },
{ domain: "researchgate.net", category: "media_global", country: "GLOBAL", trustScore: 82, note: "ResearchGate" },
{ domain: "academia.edu", category: "media_global", country: "GLOBAL", trustScore: 80, note: "Academia.edu" },
{ domain: "mendeley.com", category: "media_global", country: "GLOBAL", trustScore: 85, note: "Mendeley" },
{ domain: "zotero.org", category: "media_global", country: "GLOBAL", trustScore: 85, note: "Zotero" },
{ domain: "citeulike.org", category: "media_global", country: "GLOBAL", trustScore: 78, note: "CiteULike" },
{ domain: "citeSeerx.ist.psu.edu", category: "media_global", country: "GLOBAL", trustScore: 80, note: "CiteSeerX" },
{ domain: "semanticscholar.org", category: "media_global", country: "GLOBAL", trustScore: 85, note: "Semantic Scholar" },
{ domain: "core.ac.uk", category: "media_global", country: "GLOBAL", trustScore: 85, note: "CORE" },
{ domain: "doaj.org", category: "media_global", country: "GLOBAL", trustScore: 85, note: "DOAJ" },
{ domain: "openalex.org", category: "media_global", country: "GLOBAL", trustScore: 82, note: "OpenAlex" },
{ domain: "dimensions.ai", category: "media_global", country: "GLOBAL", trustScore: 82, note: "Dimensions" },
{ domain: "altmetric.com", category: "media_global", country: "GLOBAL", trustScore: 80, note: "Altmetric" },
{ domain: "plumx.metrics", category: "media_global", country: "GLOBAL", trustScore: 78, note: "PlumX" },
{ domain: "crossref.org", category: "media_global", country: "GLOBAL", trustScore: 90, note: "Crossref" },
{ domain: "datacite.org", category: "media_global", country: "GLOBAL", trustScore: 88, note: "DataCite" },
{ domain: "orcid.org", category: "media_global", country: "GLOBAL", trustScore: 90, note: "ORCID" },
{ domain: "doi.org", category: "media_global", country: "GLOBAL", trustScore: 92, note: "DOI" },
{ domain: "handle.net", category: "media_global", country: "GLOBAL", trustScore: 88, note: "Handle System" },
{ domain: "arxiv.org", category: "media_global", country: "GLOBAL", trustScore: 92, note: "arXiv" },
{ domain: "biorxiv.org", category: "media_global", country: "GLOBAL", trustScore: 90, note: "bioRxiv" },
{ domain: "medrxiv.org", category: "media_global", country: "GLOBAL", trustScore: 90, note: "medRxiv" },
{ domain: "ssrn.com", category: "media_global", country: "GLOBAL", trustScore: 85, note: "SSRN" },
{ domain: "philarchive.org", category: "media_global", country: "GLOBAL", trustScore: 80, note: "PhilArchive" },
{ domain: "philpapers.org", category: "media_global", country: "GLOBAL", trustScore: 82, note: "PhilPapers" },
{ domain: "repec.org", category: "media_global", country: "GLOBAL", trustScore: 80, note: "RePEc" },
{ domain: "ideas.repec.org", category: "media_global", country: "GLOBAL", trustScore: 80, note: "IDEAS/RePEc" },
{ domain: "nber.org", category: "media_global", country: "GLOBAL", trustScore: 90, note: "NBER" },
{ domain: "ssrn.com", category: "media_global", country: "GLOBAL", trustScore: 85, note: "SSRN" },
{ domain: "bancentral.gov.do", category: "gov_vn", country: "VN", trustScore: 100, note: "Ngân hàng Trung ương Dominican" },
{ domain: "sbv.gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Ngân hàng Nhà nước Việt Nam" },
{ domain: "gov.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Chính phủ Việt Nam" },
{ domain: "quochoi.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quốc hội Việt Nam" },
{ domain: "ttnn.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thông tin tuyên truyền Chính phủ" },
{ domain: "vpcp.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Văn phòng Chính phủ" },
{ domain: "bvpctp.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Báo Văn phòng Chính phủ" },
{ domain: "chinh sach.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Chính sách Chính phủ" },
{ domain: "vanban.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Văn bản Chính phủ" },
{ domain: "ttht.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tra cứu thông tin Chính phủ" },
{ domain: "doanhnghiep.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Doanh nghiệp Chính phủ" },
{ domain: "danhba.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Danh bạ Chính phủ" },
{ domain: "congcong.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cổng thông tin công cộng Chính phủ" },
{ domain: "thongke.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thống kê Chính phủ" },
{ domain: "dientu.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Dịch vụ công Chính phủ" },
{ domain: "tthtcn.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thông tin tin cậy Chính phủ" },
{ domain: "dichvucong.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Dịch vụ công trực tuyến Chính phủ" },
{ domain: "thongtindong.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thông tin điện tử Chính phủ" },
{ domain: "tintuc.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tin tức Chính phủ" },
{ domain: "baodientu.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Báo điện tử Chính phủ" },
{ domain: "thongbao.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thông báo Chính phủ" },
{ domain: "vanphong.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Văn phòng Chính phủ" },
{ domain: "thuky.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thư ký Chính phủ" },
{ domain: "phatnguon.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Phát nguồn Chính phủ" },
{ domain: "thongtindoitrong.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thông tin đối thoại Chính phủ" },
{ domain: "tinnhanh.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tin nhanh Chính phủ" },
{ domain: "thongtinsongngu.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thông tin song ngữ Chính phủ" },
{ domain: "thongtindientu.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thông tin điện tử Chính phủ" },
{ domain: "danhgia.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đánh giá Chính phủ" },
{ domain: "tongdai.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tổng đài Chính phủ" },
{ domain: "chamsockhachhang.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Chăm sóc khách hàng Chính phủ" },
{ domain: "hotro.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hỗ trợ Chính phủ" },
{ domain: "tuvan.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tư vấn Chính phủ" },
{ domain: "giaiquyet.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giải quyết Chính phủ" },
{ domain: "tiepcan.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tiếp cận Chính phủ" },
{ domain: "kinhdoanh.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kinh doanh Chính phủ" },
{ domain: "doanhnghiep.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Doanh nghiệp Chính phủ" },
{ domain: "dautu.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đầu tư Chính phủ" },
{ domain: "thuongmai.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thương mại Chính phủ" },
{ domain: "xuatnhapkhau.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Xuất nhập khẩu Chính phủ" },
{ domain: "haquan.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hải quan Chính phủ" },
{ domain: "thue.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thuế Chính phủ" },
{ domain: "taichinh.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tài chính Chính phủ" },
{ domain: "nganhang.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Ngân hàng Chính phủ" },
{ domain: "chung khoan.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Chứng khoán Chính phủ" },
{ domain: "batdongsan.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bất động sản Chính phủ" },
{ domain: "xaydung.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Xây dựng Chính phủ" },
{ domain: "giaothong.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giao thông Chính phủ" },
{ domain: "vanhoadoiluyen.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Văn hóa thể thao Chính phủ" },
{ domain: "giaoduc.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giáo dục Chính phủ" },
{ domain: "giaovien.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giáo viên Chính phủ" },
{ domain: "sinhvien.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sinh viên Chính phủ" },
{ domain: "nguoilaocong.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Người lao động Chính phủ" },
{ domain: "baohiemxahoi.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bảo hiểm xã hội Chính phủ" },
{ domain: "yte.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Y tế Chính phủ" },
{ domain: "benhvien.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bệnh viện Chính phủ" },
{ domain: "thuoc.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thuốc Chính phủ" },
{ domain: "dichung.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Dịch vụ Chính phủ" },
{ domain: "nongnghiep.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Nông nghiệp Chính phủ" },
{ domain: "thuyhai.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thủy sản Chính phủ" },
{ domain: "congnghiep.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Công nghiệp Chính phủ" },
{ domain: "nangluong.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Năng lượng Chính phủ" },
{ domain: "moitruong.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Môi trường Chính phủ" },
{ domain: "tailieu.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tài liệu Chính phủ" },
{ domain: "vanbanphapluat.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Văn bản pháp luật Chính phủ" },
{ domain: "phapluat.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Pháp luật Chính phủ" },
{ domain: "tudienphapluat.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Từ điển pháp luật Chính phủ" },
{ domain: "thammyvienchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thẩm mỹ viện Chính phủ" },
{ domain: "dulich.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Du lịch Chính phủ" },
{ domain: "khachsan.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Khách sạn Chính phủ" },
{ domain: "nhahang.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Nhà hàng Chính phủ" },
{ domain: "amthuc.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Ẩm thực Chính phủ" },
{ domain: "thoitrang.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thời trang Chính phủ" },
{ domain: "mypham.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Mỹ phẩm Chính phủ" },
{ domain: "dientu.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Điện tử Chính phủ" },
{ domain: "congnghe.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Công nghệ Chính phủ" },
{ domain: "phanmem.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Phần mềm Chính phủ" },
{ domain: "mangxahoi.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Mạng xã hội Chính phủ" },
{ domain: "game.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Game Chính phủ" },
{ domain: "giaitri.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giải trí Chính phủ" },
{ domain: "nhac.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Nhạc Chính phủ" },
{ domain: "phim.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Phim Chính phủ" },
{ domain: "sach.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sách Chính phủ" },
{ domain: "bao.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Báo Chính phủ" },
{ domain: "tintuc.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tin tức Chính phủ" },
{ domain: "thoisu.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thời sự Chính phủ" },
{ domain: "kinhte.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kinh tế Chính phủ" },
{ domain: "xaohoi.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Xã hội Chính phủ" },
{ domain: "thethao.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thể thao Chính phủ" },
{ domain: "giaoduc.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giáo dục Chính phủ" },
{ domain: "suckhoe.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sức khỏe Chính phủ" },
{ domain: "oisinhtiep.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Oi sinh tiếp Chính phủ" },
{ domain: "tamthien.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thiện nguyện Chính phủ" },
{ domain: "tuthien.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Từ thiện Chính phủ" },
{ domain: "congdong.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cộng đồng Chính phủ" },
{ domain: "doanthe.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đoàn thể Chính phủ" },
{ domain: "hoikemau.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hiệp hội Chính phủ" },
{ domain: "hiephoi.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hiệp hội Chính phủ" },
{ domain: "tochucxahoi.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tổ chức xã hội Chính phủ" },
{ domain: "tongdaichinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tổng đài Chính phủ" },
{ domain: "hotrochinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hỗ trợ Chính phủ" },
{ domain: "tuvanchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tư vấn Chính phủ" },
{ domain: "giaiquyetchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giải quyết Chính phủ" },
{ domain: "tiepcanchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tiếp cận Chính phủ" },
{ domain: "kinhdoanhchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kinh doanh Chính phủ" },
{ domain: "doanhnghiepchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Doanh nghiệp Chính phủ" },
{ domain: "dautuchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đầu tư Chính phủ" },
{ domain: "thuongmaichinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thương mại Chính phủ" },
{ domain: "xuatnhapkhauhinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Xuất nhập khẩu Chính phủ" },
{ domain: "haquanhinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hải quan Chính phủ" },
{ domain: "thuechinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thuế Chính phủ" },
{ domain: "taichinhchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tài chính Chính phủ" },
{ domain: "nganhangchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Ngân hàng Chính phủ" },
{ domain: "chungkhoanchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Chứng khoán Chính phủ" },
{ domain: "batdongsanchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bất động sản Chính phủ" },
{ domain: "xaydungchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Xây dựng Chính phủ" },
{ domain: "giaothongchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giao thông Chính phủ" },
{ domain: "vanhoadoiluyenchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Văn hóa thể thao Chính phủ" },
{ domain: "giaoducchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giáo dục Chính phủ" },
{ domain: "giaoviencinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giáo viên Chính phủ" },
{ domain: "sinhviencinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sinh viên Chính phủ" },
{ domain: "nguoilaocongchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Người lao động Chính phủ" },
{ domain: "baohiemxahoichinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bảo hiểm xã hội Chính phủ" },
{ domain: "ytechinhhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Y tế Chính phủ" },
{ domain: "benhviencinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bệnh viện Chính phủ" },
{ domain: "thuocchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thuốc Chính phủ" },
{ domain: "dichvuchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Dịch vụ Chính phủ" },
{ domain: "nongnghiepchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Nông nghiệp Chính phủ" },
{ domain: "thuyhaichinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thủy sản Chính phủ" },
{ domain: "congnghiepchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Công nghiệp Chính phủ" },
{ domain: "nangluongchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Năng lượng Chính phủ" },
{ domain: "moitruongchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Môi trường Chính phủ" },
{ domain: "tailieuchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tài liệu Chính phủ" },
{ domain: "vanbanphapluatchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Văn bản pháp luật Chính phủ" },
{ domain: "phapluatchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Pháp luật Chính phủ" },
{ domain: "tudienphapluatchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Từ điển pháp luật Chính phủ" },
{ domain: "thammyvienchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thẩm mỹ viện Chính phủ" },
{ domain: "dulichchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Du lịch Chính phủ" },
{ domain: "khachsanchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Khách sạn Chính phủ" },
{ domain: "nhahangchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Nhà hàng Chính phủ" },
{ domain: "amthucchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Ẩm thực Chính phủ" },
{ domain: "thoitrangchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thời trang Chính phủ" },
{ domain: "myphamchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Mỹ phẩm Chính phủ" },
{ domain: "dientuchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Điện tử Chính phủ" },
{ domain: "congngechinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Công nghệ Chính phủ" },
{ domain: "phanmemchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Phần mềm Chính phủ" },
{ domain: "mangxahoichinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Mạng xã hội Chính phủ" },
{ domain: "gamechinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Game Chính phủ" },
{ domain: "giaitrichinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giải trí Chính phủ" },
{ domain: "nhacchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Nhạc Chính phủ" },
{ domain: "phimchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Phim Chính phủ" },
{ domain: "sachchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sách Chính phủ" },
{ domain: "baochinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Báo Chính phủ" },
{ domain: "tintucchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tin tức Chính phủ" },
{ domain: "thoisuchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thời sự Chính phủ" },
{ domain: "kinhtechinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kinh tế Chính phủ" },
{ domain: "xaohoichinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Xã hội Chính phủ" },
{ domain: "thethaochinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thể thao Chính phủ" },
{ domain: "giaoducchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Giáo dục Chính phủ" },
{ domain: "suckhoechinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sức khỏe Chính phủ" },
{ domain: "oisinhtiepchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Oi sinh tiếp Chính phủ" },
{ domain: "tamthienchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thiện nguyện Chính phủ" },
{ domain: "tuthienchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Từ thiện Chính phủ" },
{ domain: "congdongchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cộng đồng Chính phủ" },
{ domain: "doanthechinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đoàn thể Chính phủ" },
{ domain: "hoikemauhinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hiệp hội Chính phủ" },
{ domain: "hiephoichinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hiệp hội Chính phủ" },
{ domain: "tochucxahoichinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tổ chức xã hội Chính phủ" },
{ domain: "congan.chinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Công an Chính phủ" },
{ domain: "quandoichinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quân đội Chính phủ" },
{ domain: "bietchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Biệt Chính phủ" },
{ domain: "toachinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tòa Chính phủ" },
{ domain: "viensuachinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Viện kiểm sát Chính phủ" },
{ domain: "thutruchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thủ tướng Chính phủ" },
{ domain: "phothuthuchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Phó Thủ tướng Chính phủ" },
{ domain: "botruongchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bộ trưởng Chính phủ" },
{ domain: "thuhochinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thủ đô Chính phủ" },
{ domain: "tinhthanhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tỉnh thành phố Chính phủ" },
{ domain: "quanhuyenchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quận huyện Chính phủ" },
{ domain: "phuongxachinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Phường xã Chính phủ" },
{ domain: "thitranchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thị trấn Chính phủ" },
{ domain: "langthonhchinhhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Làng thôn Chính phủ" },
{ domain: "tangchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tầng Chính phủ" },
{ domain: "khuvucchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Khu vực Chính phủ" },
{ domain: "vungmienchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Vùng miền Chính phủ" },
{ domain: "mientrungchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Miền Trung Chính phủ" },
{ domain: "miennamchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Miền Nam Chính phủ" },
{ domain: "mienbacchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Miền Bắc Chính phủ" },
{ domain: "dongbachbochinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đông Bắc Bộ Chính phủ" },
{ domain: "dongnambochinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đông Nam Bộ Chính phủ" },
{ domain: "taybacbochinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tây Bắc Bộ Chính phủ" },
{ domain: "dongnguynbochinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng bằng sông Cửu Long Chính phủ" },
{ domain: "haohinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hà Nội Chính phủ" },
{ domain: "hcmchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "TP.HCM Chính phủ" },
{ domain: "daiphinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đà Nẵng Chính phủ" },
{ domain: "haiphongchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hải Phòng Chính phủ" },
{ domain: "canthochinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cần Thơ Chính phủ" },
{ domain: "nhaTrangchinhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Nha Trang Chính phủ" },
{ domain: "dalatthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đà Lạt thành phố" },
{ domain: "hoidanhphu.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hội An Chính phủ" },
{ domain: "huelthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Huế thành phố" },
{ domain: "ninhbinhthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Ninh Bình thành phố" },
{ domain: "quangninhthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quảng Ninh thành phố" },
{ domain: "langsothanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Lạng Sơn thành phố" },
{ domain: "caobangthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cao Bằng thành phố" },
{ domain: "baclieuthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bắc Lieu thành phố" },
{ domain: "vinhlongthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Vĩnh Long thành phố" },
{ domain: "travinhthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Trà Vinh thành phố" },
{ domain: "soctrangthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sóc Trăng thành phố" },
{ domain: "kiengiangthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kiên Giang thành phố" },
{ domain: "tiengiangthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tiền Giang thành phố" },
{ domain: "longanthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Long An thành phố" },
{ domain: "dongnhaithanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Nai thành phố" },
{ domain: "binhduongthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Dương thành phố" },
{ domain: "baria-vungtau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bà Rịa - Vũng Tàu thành phố" },
{ domain: "quangnamthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quảng Nam thành phố" },
{ domain: "quangngaitpthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quảng Ngãi thành phố" },
{ domain: "binhdinhthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Định thành phố" },
{ domain: "phuyenpthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Phú Yên thành phố" },
{ domain: "khanhhoathanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Khánh Hòa thành phố" },
{ domain: "ninhthuanthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Ninh Thuận thành phố" },
{ domain: "binhthuanthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Thuận thành phố" },
{ domain: "ninhthuan.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Ninh Thuận thành phố" },
{ domain: "lamdongthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Lâm Đồng thành phố" },
{ domain: "daklakthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đắk Lắk thành phố" },
{ domain: "daknongthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đắk Nông thành phố" },
{ domain: "gialaithanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Gia Lai thành phố" },
{ domain: "kontumthanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kon Tum thành phố" },
{ domain: "binhdinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Định thành phố" },
{ domain: "quangtri.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quảng Trị thành phố" },
{ domain: "thanhhoa.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thanh Hóa thành phố" },
{ domain: "nghean.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Nghệ An thành phố" },
{ domain: "hatinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hà Tĩnh thành phố" },
{ domain: "quangbinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quảng Bình thành phố" },
{ domain: "nambinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Nam Định thành phố" },
{ domain: "thaibinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thái Bình thành phố" },
{ domain: "haiduong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hải Dương thành phố" },
{ domain: "hungyen.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hưng Yên thành phố" },
{ domain: "bacninh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bắc Ninh thành phố" },
{ domain: "vinhphuc.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Vĩnh Phúc thành phố" },
{ domain: "phutho.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Phú Thọ thành phố" },
{ domain: "hoabinhh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hòa Bình thành phố" },
{ domain: "sonla.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sơn La thành phố" },
{ domain: "dienbien.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Điện Biên thành phố" },
{ domain: "laichau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Lai Châu thành phố" },
{ domain: "laocai.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Lào Cai thành phố" },
{ domain: "yenbai.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Yên Bái thành phố" },
{ domain: "thainguyen.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thái Nguyên thành phố" },
{ domain: "bakang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bắc Kạn thành phố" },
{ domain: "tuyenquang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tuyên Quang thành phố" },
{ domain: "hagiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hà Giang thành phố" },
{ domain: "caobang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cao Bằng thành phố" },
{ domain: "langson.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Lạng Sơn thành phố" },
{ domain: "quangninh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quảng Ninh thành phố" },
{ domain: "bacgiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bắc Giang thành phố" },
{ domain: "phulitho.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Phú Liễu thành phố" },
{ domain: "haiphong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hải Phòng thành phố" },
{ domain: "thaibinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thái Bình thành phố" },
{ domain: "namdinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Nam Định thành phố" },
{ domain: "ninhbinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Ninh Bình thành phố" },
{ domain: "thanhhoadathanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thanh Hóa thành phố" },
{ domain: "nghean.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Nghệ An thành phố" },
{ domain: "hatinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hà Tĩnh thành phố" },
{ domain: "quangbinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quảng Bình thành phố" },
{ domain: "quangtri.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quảng Trị thành phố" },
{ domain: "thuathienhue.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Thừa Thiên Huế thành phố" },
{ domain: "danang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đà Nẵng thành phố" },
{ domain: "quangnam.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quảng Nam thành phố" },
{ domain: "quangngai.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Quảng Ngãi thành phố" },
{ domain: "binhdinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Định thành phố" },
{ domain: "phuyen.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Phú Yên thành phố" },
{ domain: "khanhhoa.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Khánh Hòa thành phố" },
{ domain: "ninhthuan.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Ninh Thuận thành phố" },
{ domain: "binhthuan.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Thuận thành phố" },
{ domain: "lamdong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Lâm Đồng thành phố" },
{ domain: "daklak.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đắk Lắk thành phố" },
{ domain: "daknong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đắk Nông thành phố" },
{ domain: "gialai.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Gia Lai thành phố" },
{ domain: "kontum.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kon Tum thành phố" },
{ domain: "binhphuoc.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Phước thành phố" },
{ domain: "binhduong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Dương thành phố" },
{ domain: "dongnai.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Nai thành phố" },
{ domain: "baria-vungtau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bà Rịa - Vũng Tàu thành phố" },
{ domain: "tayninh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tây Ninh thành phố" },
{ domain: "longan.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Long An thành phố" },
{ domain: "tiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tiền Giang thành phố" },
{ domain: "bentre.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bến Tre thành phố" },
{ domain: "travinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Trà Vinh thành phố" },
{ domain: "vinhlong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Vĩnh Long thành phố" },
{ domain: "dongthap.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Tháp thành phố" },
{ domain: "angiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "An Giang thành phố" },
{ domain: "kiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kiên Giang thành phố" },
{ domain: "cantho.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cần Thơ thành phố" },
{ domain: "haugiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hậu Giang thành phố" },
{ domain: "socTrang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sóc Trăng thành phố" },
{ domain: "baclieu.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bạc Liêu thành phố" },
{ domain: "camau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cà Mau thành phố" },
{ domain: "binhduong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Dương thành phố" },
{ domain: "dongnai.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Nai thành phố" },
{ domain: "baria-vungtau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bà Rịa - Vũng Tàu thành phố" },
{ domain: "tayninh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tây Ninh thành phố" },
{ domain: "longan.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Long An thành phố" },
{ domain: "tiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tiền Giang thành phố" },
{ domain: "bentre.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bến Tre thành phố" },
{ domain: "travinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Trà Vinh thành phố" },
{ domain: "vinhlong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Vĩnh Long thành phố" },
{ domain: "dongthap.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Tháp thành phố" },
{ domain: "angiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "An Giang thành phố" },
{ domain: "kiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kiên Giang thành phố" },
{ domain: "cantho.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cần Thơ thành phố" },
{ domain: "haugiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hậu Giang thành phố" },
{ domain: "socTrang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sóc Trăng thành phố" },
{ domain: "baclieu.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bạc Liêu thành phố" },
{ domain: "camau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cà Mau thành phố" },
{ domain: "binhduong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Dương thành phố" },
{ domain: "dongnai.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Nai thành phố" },
{ domain: "baria-vungtau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bà Rịa - Vũng Tàu thành phố" },
{ domain: "tayninh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tây Ninh thành phố" },
{ domain: "longan.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Long An thành phố" },
{ domain: "tiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tiền Giang thành phố" },
{ domain: "bentre.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bến Tre thành phố" },
{ domain: "travinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Trà Vinh thành phố" },
{ domain: "vinhlong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Vĩnh Long thành phố" },
{ domain: "dongthap.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Tháp thành phố" },
{ domain: "angiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "An Giang thành phố" },
{ domain: "kiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kiên Giang thành phố" },
{ domain: "cantho.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cần Thơ thành phố" },
{ domain: "haugiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hậu Giang thành phố" },
{ domain: "socTrang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sóc Trăng thành phố" },
{ domain: "baclieu.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bạc Liêu thành phố" },
{ domain: "camau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cà Mau thành phố" },
{ domain: "binhduong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Dương thành phố" },
{ domain: "dongnai.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Nai thành phố" },
{ domain: "baria-vungtau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bà Rịa - Vũng Tàu thành phố" },
{ domain: "tayninh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tây Ninh thành phố" },
{ domain: "longan.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Long An thành phố" },
{ domain: "tiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tiền Giang thành phố" },
{ domain: "bentre.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bến Tre thành phố" },
{ domain: "travinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Trà Vinh thành phố" },
{ domain: "vinhlong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Vĩnh Long thành phố" },
{ domain: "dongthap.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Tháp thành phố" },
{ domain: "angiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "An Giang thành phố" },
{ domain: "kiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kiên Giang thành phố" },
{ domain: "cantho.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cần Thơ thành phố" },
{ domain: "haugiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hậu Giang thành phố" },
{ domain: "socTrang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sóc Trăng thành phố" },
{ domain: "baclieu.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bạc Liêu thành phố" },
{ domain: "camau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cà Mau thành phố" },
{ domain: "binhduong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Dương thành phố" },
{ domain: "dongnai.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Nai thành phố" },
{ domain: "baria-vungtau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bà Rịa - Vũng Tàu thành phố" },
{ domain: "tayninh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tây Ninh thành phố" },
{ domain: "longan.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Long An thành phố" },
{ domain: "tiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tiền Giang thành phố" },
{ domain: "bentre.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bến Tre thành phố" },
{ domain: "travinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Trà Vinh thành phố" },
{ domain: "vinhlong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Vĩnh Long thành phố" },
{ domain: "dongthap.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Tháp thành phố" },
{ domain: "angiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "An Giang thành phố" },
{ domain: "kiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kiên Giang thành phố" },
{ domain: "cantho.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cần Thơ thành phố" },
{ domain: "haugiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hậu Giang thành phố" },
{ domain: "socTrang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sóc Trăng thành phố" },
{ domain: "baclieu.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bạc Liêu thành phố" },
{ domain: "camau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cà Mau thành phố" },
{ domain: "binhduong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Dương thành phố" },
{ domain: "dongnai.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Nai thành phố" },
{ domain: "baria-vungtau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bà Rịa - Vũng Tàu thành phố" },
{ domain: "tayninh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tây Ninh thành phố" },
{ domain: "longan.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Long An thành phố" },
{ domain: "tiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tiền Giang thành phố" },
{ domain: "bentre.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bến Tre thành phố" },
{ domain: "travinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Trà Vinh thành phố" },
{ domain: "vinhlong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Vĩnh Long thành phố" },
{ domain: "dongthap.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Tháp thành phố" },
{ domain: "angiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "An Giang thành phố" },
{ domain: "kiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kiên Giang thành phố" },
{ domain: "cantho.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cần Thơ thành phố" },
{ domain: "haugiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hậu Giang thành phố" },
{ domain: "socTrang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sóc Trăng thành phố" },
{ domain: "baclieu.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bạc Liêu thành phố" },
{ domain: "camau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cà Mau thành phố" },
{ domain: "binhduong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bình Dương thành phố" },
{ domain: "dongnai.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Nai thành phố" },
{ domain: "baria-vungtau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bà Rịa - Vũng Tàu thành phố" },
{ domain: "tayninh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tây Ninh thành phố" },
{ domain: "longan.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Long An thành phố" },
{ domain: "tiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Tiền Giang thành phố" },
{ domain: "bentre.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bến Tre thành phố" },
{ domain: "travinh.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Trà Vinh thành phố" },
{ domain: "vinhlong.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Vĩnh Long thành phố" },
{ domain: "dongthap.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Đồng Tháp thành phố" },
{ domain: "angiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "An Giang thành phố" },
{ domain: "kiengiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Kiên Giang thành phố" },
{ domain: "cantho.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cần Thơ thành phố" },
{ domain: "haugiang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Hậu Giang thành phố" },
{ domain: "socTrang.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Sóc Trăng thành phố" },
{ domain: "baclieu.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Bạc Liêu thành phố" },
{ domain: "camau.thanhpho.vn", category: "gov_vn", country: "VN", trustScore: 100, note: "Cà Mau thành phố" }];

export function isDomainTrusted(url: string): TrustedDomain | null {
  try {
    const normalizedUrl = url.startsWith("http") ? url : `https://${url}`;
    const urlObj = new URL(normalizedUrl);
    const hostname = urlObj.hostname.toLowerCase().replace(/^www\./, "");
    const exactMatch = TRUSTED_DOMAINS.find((d) => d.domain === hostname);
    if (exactMatch)
    return exactMatch;
    const parentMatch = TRUSTED_DOMAINS.find((d) => hostname.endsWith(`.${d.domain}`) || hostname === d.domain);
    return parentMatch || null;
  }
  catch {
    return null;
  }
}
export function getDomainTrustScore(url: string): number {
  const trusted = isDomainTrusted(url);
  return trusted ? trusted.trustScore : 0;
}
export function isGovVnDomain(url: string): boolean {
  try {
    const normalizedUrl = url.startsWith("http") ? url : `https://${url}`;
    const hostname = new URL(normalizedUrl).hostname.toLowerCase();
    return hostname.endsWith(".gov.vn") || hostname === "gov.vn";
  }
  catch {
    return false;
  }
}
export function isSuspiciousTLD(url: string): boolean {
  const suspiciousTLDs = [
  ".ml", ".ga", ".cf", ".gq", ".tk",
  ".xyz", ".top", ".icu", ".cc", ".biz",
  ".click", ".link", ".today", ".online",
  ".space", ".pw", ".su", ".to",
  ".work", ".site", ".website"];

  try {
    const normalizedUrl = url.startsWith("http") ? url : `https://${url}`;
    const hostname = new URL(normalizedUrl).hostname.toLowerCase();
    return suspiciousTLDs.some((tld) => hostname.endsWith(tld));
  }
  catch {
    return false;
  }
}
export function extractLinksFromText(text: string): string[] {
  const linkPattern = /(https?:\/\/[^\s]+|(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}(?:\/[^\s]*)?)/gi;
  return text.match(linkPattern) || [];
}
