// ============ BRAND PATTERNS — Typosquatting & Brand Impersonation Detection ============
// 120+ thương hiệu, 5 nhóm. Tách riêng để hot-reload và bảo trì.
// Mỗi pattern: brand, keywords (đã lowercase, bỏ dấu), officialDomains.
module.exports = {
  GROUPS: {
    BANKING: 'Ngân hàng & Fintech',
    LOGISTICS: 'Logistics / Chuyển phát',
    ECOMMERCE: 'E-Commerce & Bán lẻ',
    SOCIAL: 'Mạng xã hội & Big Tech',
    GOV_SERVICES: 'Dịch vụ công & Bảo hiểm'
  },

  PATTERNS: [
    // ============ NHÓM NGÂN HÀNG & FINTECH ============
    { brand: 'Vietcombank', group: 'BANKING', keywords: ['vietcombank', 'vcb', 'vcbonline', 'vietcombankvn'], officialDomains: ['vietcombank.com.vn'] },
    { brand: 'MB Bank', group: 'BANKING', keywords: ['mbbank', 'mb bank', 'mbbanking', 'mb-online'], officialDomains: ['mbbank.com.vn'] },
    { brand: 'Techcombank', group: 'BANKING', keywords: ['techcombank', 'techcom', 'tcbonline'], officialDomains: ['techcombank.com.vn'] },
    { brand: 'TPBank', group: 'BANKING', keywords: ['tpbank', 'tp bank', 'tpbankonline', 'tp-online'], officialDomains: ['tpbank.com.vn'] },
    { brand: 'VietinBank', group: 'BANKING', keywords: ['vietinbank', 'vietin', 'vietinbankonline'], officialDomains: ['vietinbank.com.vn'] },
    { brand: 'Agribank', group: 'BANKING', keywords: ['agribank', 'agri bank', 'agribankonline'], officialDomains: ['agribank.com.vn'] },
    { brand: 'Sacombank', group: 'BANKING', keywords: ['sacombank', 'sacom', 'sacombankonline'], officialDomains: ['sacombank.com.vn'] },
    { brand: 'BIDV', group: 'BANKING', keywords: ['bidv', 'bidvonline', 'bidvbank'], officialDomains: ['bidv.com.vn'] },
    { brand: 'ACB', group: 'BANKING', keywords: ['acb', 'acbbank', 'acbonline'], officialDomains: ['acb.com.vn'] },
    { brand: 'VPBank', group: 'BANKING', keywords: ['vpbank', 'vp bank', 'vpbankonline'], officialDomains: ['vpbank.com.vn'] },
    { brand: 'VIB', group: 'BANKING', keywords: ['vib', 'vibbank', 'vibonline'], officialDomains: ['vib.com.vn'] },
    { brand: 'HDBank', group: 'BANKING', keywords: ['hdbank', 'hd bank', 'hdbanking'], officialDomains: ['hdbank.com.vn'] },
    { brand: 'Eximbank', group: 'BANKING', keywords: ['eximbank', 'exim bank'], officialDomains: ['eximbank.com.vn'] },
    { brand: 'SHB', group: 'BANKING', keywords: ['shb', 'shbbank', 'shbonline'], officialDomains: ['shb.com.vn'] },
    { brand: 'MSB', group: 'BANKING', keywords: ['msb', 'msbbank', 'maritimebank'], officialDomains: ['msb.com.vn'] },
    { brand: 'OCB', group: 'BANKING', keywords: ['ocb', 'ocbbank', 'ocbonline'], officialDomains: ['ocb.com.vn'] },
    { brand: 'SCB', group: 'BANKING', keywords: ['scb', 'sacombank'], officialDomains: ['scb.com.vn'] },
    { brand: 'Nam A Bank', group: 'BANKING', keywords: ['namabank', 'nama bank', 'nam a bank'], officialDomains: ['namabank.com.vn'] },
    { brand: 'Viet Capital Bank', group: 'BANKING', keywords: ['vietcapitalbank', 'vietcapital'], officialDomains: ['vietcapitalbank.com.vn'] },
    { brand: 'Standard Chartered', group: 'BANKING', keywords: ['standardchartered', 'scb'], officialDomains: ['sc.com', 'standardchartered.com'] },
    { brand: 'HSBC', group: 'BANKING', keywords: ['hsbc'], officialDomains: ['hsbc.com.vn', 'hsbc.com'] },
    { brand: 'CitiBank', group: 'BANKING', keywords: ['citibank', 'citi'], officialDomains: ['citibank.com.vn', 'citibank.com'] },
    { brand: 'MoMo', group: 'BANKING', keywords: ['momo', 'momo wallet', 'momowallet', 'momo-wallet'], officialDomains: ['momo.vn'] },
    { brand: 'ZaloPay', group: 'BANKING', keywords: ['zalopay', 'zalo pay', 'zalopay.vn'], officialDomains: ['zalopay.vn', 'zalopay.com.vn'] },
    { brand: 'VNPay', group: 'BANKING', keywords: ['vnpay', 'vn pay', 'vnpayqr'], officialDomains: ['vnpay.vn', 'vnpay.vnpay.vn'] },
    { brand: 'Viettel Money', group: 'BANKING', keywords: ['viettelmoney', 'viettel money', 'vtmoney'], officialDomains: ['viettelmoney.vn', 'viettel.vn'] },
    { brand: 'ShopeePay', group: 'BANKING', keywords: ['shopeepay', 'shopee pay', 'airpay'], officialDomains: ['shopee.vn'] },
    { brand: 'PayPal', group: 'BANKING', keywords: ['paypal'], officialDomains: ['paypal.com'] },
    { brand: 'GrabPay', group: 'BANKING', keywords: ['grabpay', 'grab pay'], officialDomains: ['grab.com'] },
    { brand: 'Apple Pay', group: 'BANKING', keywords: ['applepay', 'apple pay'], officialDomains: ['apple.com'] },
    { brand: 'Smart Banking', group: 'BANKING', keywords: ['smartbanking', 'smart-banking'], officialDomains: ['smartbanking.com.vn'] },
    { brand: 'Mcredit', group: 'BANKING', keywords: ['mcredit'], officialDomains: ['mcredit.com.vn'] },
    { brand: 'FE Credit', group: 'BANKING', keywords: ['fecredit', 'fe credit'], officialDomains: ['fecredit.com.vn'] },
    { brand: 'Home Credit', group: 'BANKING', keywords: ['homecredit', 'home credit'], officialDomains: ['homecredit.vn'] },

    // ============ NHÓM LOGISTICS / CHUYỂN PHÁT ============
    { brand: 'Giao hàng Tiết kiệm', group: 'LOGISTICS', keywords: ['giaohangtietkiem', 'ghtk', 'giao hang tiet kiem', 'tietkiem', 'giaohang-tietkiem', 'ctygiaohangtietkiem', 'giaohangtietkiemmi'], officialDomains: ['giaohangtietkiem.vn', 'ghtk.vn'] },
    { brand: 'GHN', group: 'LOGISTICS', keywords: ['ghn', 'giaohangnhanh', 'giao hang nhanh', 'ghnexpress'], officialDomains: ['ghn.vn', 'giaohangnhanh.vn'] },
    { brand: 'Viettel Post', group: 'LOGISTICS', keywords: ['viettelpost', 'viettel post', 'viettelpos'], officialDomains: ['viettelpost.com.vn', 'viettelpost.vn'] },
    { brand: 'J&T Express', group: 'LOGISTICS', keywords: ['jtexpress', 'jt express', 'jt-express'], officialDomains: ['jtexpress.vn'] },
    { brand: 'Ninja Van', group: 'LOGISTICS', keywords: ['ninjavan', 'ninja van'], officialDomains: ['ninjavan.vn'] },
    { brand: 'Shopee Express', group: 'LOGISTICS', keywords: ['shopeexpress', 'shopee express', 'spx'], officialDomains: ['shopee.vn'] },
    { brand: 'VNPost', group: 'LOGISTICS', keywords: ['vnpost', 'vn post', 'buudien', 'buu dien'], officialDomains: ['vnpost.vn'] },
    { brand: 'Lalamove', group: 'LOGISTICS', keywords: ['lalamove', 'lala move'], officialDomains: ['lalamove.com'] },
    { brand: 'AhaMove', group: 'LOGISTICS', keywords: ['ahamove', 'aha move', 'ahavn'], officialDomains: ['ahamove.com'] },
    { brand: 'Best Express', group: 'LOGISTICS', keywords: ['bestexpress', 'best express'], officialDomains: ['bestexpress.vn'] },
    { brand: 'GrabExpress', group: 'LOGISTICS', keywords: ['grabexpress', 'grab express'], officialDomains: ['grab.com'] },
    { brand: 'DHL', group: 'LOGISTICS', keywords: ['dhl'], officialDomains: ['dhl.com'] },
    { brand: 'FedEx', group: 'LOGISTICS', keywords: ['fedex'], officialDomains: ['fedex.com'] },
    { brand: 'TikiNOW', group: 'LOGISTICS', keywords: ['tikinow', 'tiki now'], officialDomains: ['tiki.vn'] },
    { brand: 'Vietnam Post', group: 'LOGISTICS', keywords: ['vietnampost', 'vietnam post'], officialDomains: ['vnpost.vn', 'vietnampost.vn'] },

    // ============ NHÓM E-COMMERCE & BÁN LẺ ============
    { brand: 'Shopee', group: 'ECOMMERCE', keywords: ['shopee', 'shopeevn'], officialDomains: ['shopee.vn'] },
    { brand: 'Lazada', group: 'ECOMMERCE', keywords: ['lazada', 'lazada-vn'], officialDomains: ['lazada.vn'] },
    { brand: 'Tiki', group: 'ECOMMERCE', keywords: ['tiki', 'tiki.vn'], officialDomains: ['tiki.vn'] },
    { brand: 'TikTok Shop', group: 'ECOMMERCE', keywords: ['tiktokshop', 'tiktok shop', 'tiktok'], officialDomains: ['tiktok.com', 'tiktokshop.com'] },
    { brand: 'Sendo', group: 'ECOMMERCE', keywords: ['sendo'], officialDomains: ['sendo.vn'] },
    { brand: 'Thế Giới Di Động', group: 'ECOMMERCE', keywords: ['thegioididong', 'tgdd', 'the gioi di dong'], officialDomains: ['thegioididong.com'] },
    { brand: 'FPT Shop', group: 'ECOMMERCE', keywords: ['fptshop', 'fpt shop'], officialDomains: ['fptshop.com.vn'] },
    { brand: 'Điện Máy Xanh', group: 'ECOMMERCE', keywords: ['dienmayxanh', 'dien may xanh', 'dmx'], officialDomains: ['dienmayxanh.com'] },
    { brand: 'Nguyễn Kim', group: 'ECOMMERCE', keywords: ['nguyenkim', 'nguyen kim'], officialDomains: ['nguyenkim.com'] },
    { brand: 'CellphoneS', group: 'ECOMMERCE', keywords: ['cellphones', 'cellphone s'], officialDomains: ['cellphones.com.vn'] },
    { brand: 'MediaMart', group: 'ECOMMERCE', keywords: ['mediamart'], officialDomains: ['mediamart.vn'] },
    { brand: 'Bách Hóa Xanh', group: 'ECOMMERCE', keywords: ['bachhoaxanh', 'bach hoa xanh', 'bhx'], officialDomains: ['bachhoaxanh.com'] },
    { brand: 'META Shop', group: 'ECOMMERCE', keywords: ['metashop', 'meta shop'], officialDomains: ['meta.vn'] },
    { brand: 'Tiki Trading', group: 'ECOMMERCE', keywords: ['tikitrading', 'tiki trading'], officialDomains: ['tiki.vn'] },
    { brand: 'GearVN', group: 'ECOMMERCE', keywords: ['gearvn'], officialDomains: ['gearvn.com'] },

    // ============ NHÓM MẠNG XÃ HỘI & BIG TECH ============
    { brand: 'Facebook', group: 'SOCIAL', keywords: ['facebook', 'fb', 'meta'], officialDomains: ['facebook.com'] },
    { brand: 'Zalo', group: 'SOCIAL', keywords: ['zalo', 'zalo.me'], officialDomains: ['zalo.me'] },
    { brand: 'Telegram', group: 'SOCIAL', keywords: ['telegram', 'tg'], officialDomains: ['telegram.org', 't.me'] },
    { brand: 'TikTok', group: 'SOCIAL', keywords: ['tiktok', 'tiktok-vn'], officialDomains: ['tiktok.com'] },
    { brand: 'Google', group: 'SOCIAL', keywords: ['google', 'gmail', 'youtube', 'googlesupport'], officialDomains: ['google.com', 'gmail.com', 'youtube.com'] },
    { brand: 'Apple', group: 'SOCIAL', keywords: ['apple', 'icloud', 'appstore'], officialDomains: ['apple.com'] },
    { brand: 'Microsoft', group: 'SOCIAL', keywords: ['microsoft', 'msn', 'office365', 'outlook'], officialDomains: ['microsoft.com'] },
    { brand: 'Netflix', group: 'SOCIAL', keywords: ['netflix'], officialDomains: ['netflix.com'] },
    { brand: 'Steam', group: 'SOCIAL', keywords: ['steam'], officialDomains: ['steampowered.com'] },
    { brand: 'Instagram', group: 'SOCIAL', keywords: ['instagram', 'insta'], officialDomains: ['instagram.com'] },
    { brand: 'WhatsApp', group: 'SOCIAL', keywords: ['whatsapp', 'whats app'], officialDomains: ['whatsapp.com'] },
    { brand: 'Discord', group: 'SOCIAL', keywords: ['discord'], officialDomains: ['discord.com'] },
    { brand: 'X (Twitter)', group: 'SOCIAL', keywords: ['twitter', 'x twitter'], officialDomains: ['twitter.com', 'x.com'] },
    { brand: 'LinkedIn', group: 'SOCIAL', keywords: ['linkedin'], officialDomains: ['linkedin.com'] },

    // ============ NHÓM DỊCH VỤ CÔNG & BẢO HIỂM ============
    { brand: 'Chính phủ Việt Nam', group: 'GOV_SERVICES', keywords: ['chinhphu', 'chinh phu', 'govvn', 'cong thong tin chinh phu', 'ttcp', 'baochinhphu'], officialDomains: ['chinhphu.vn', 'gov.vn', 'baochinhphu.vn'] },
    { brand: 'VSS (BHXH)', group: 'GOV_SERVICES', keywords: ['bhxh', 'baohiemxahoi', 'bao hiem xa hoi', 'vss', 'baohiem'], officialDomains: ['bhxh.gov.vn'] },
    { brand: 'VNeID', group: 'GOV_SERVICES', keywords: ['vneid', 'vneid'], officialDomains: ['vneid.gov.vn'] },
    { brand: 'Cổng DVC Quốc gia', group: 'GOV_SERVICES', keywords: ['dichvucong', 'dvc quoc gia', 'dich-vu-cong', 'congdichvucong'], officialDomains: ['dichvucong.gov.vn'] },
    { brand: 'Cảnh sát giao thông', group: 'GOV_SERVICES', keywords: ['csgt', 'canhsatgiaothong', 'canh sat giao thong', 'giaypheplaixe'], officialDomains: ['csgt.vn'] },
    { brand: 'Tổng cục Thuế', group: 'GOV_SERVICES', keywords: ['thuedientu', 'thue dien tu', 'tracuuthue', 'tongcucthue'], officialDomains: ['thuedientu.gdt.gov.vn'] },
    { brand: 'Công an điện tử', group: 'GOV_SERVICES', keywords: ['congandientu', 'cong an dien tu'], officialDomains: ['congan.gov.vn'] },
    { brand: 'Bảo hiểm xã hội VN', group: 'GOV_SERVICES', keywords: ['baohiemxahoi.vn'], officialDomains: ['baohiemxahoi.gov.vn'] },
    { brand: 'Tổng cục Hải quan', group: 'GOV_SERVICES', keywords: ['haiquan', 'hai quan', 'customs'], officialDomains: ['customs.gov.vn'] },
    { brand: 'eTax', group: 'GOV_SERVICES', keywords: ['etax', 'e tax'], officialDomains: ['etaxvn.com'] },
    { brand: 'VssID', group: 'GOV_SERVICES', keywords: ['vssid'], officialDomains: ['vssid.vn'] },
    { brand: 'Sổ sức khỏe điện tử', group: 'GOV_SERVICES', keywords: ['sosuckhoedientu', 'so suc khoe dien tu', 'suckhoedientu'], officialDomains: ['sosuckhoedientu.vn'] },
    { brand: 'Cơ quan BHXH VN', group: 'GOV_SERVICES', keywords: ['baohiemxahoi'], officialDomains: ['baohiemxahoi.gov.vn'] },

    // ============ NHÓM CRYPTO / VÍ ĐIỆN TỬ ============
    { brand: 'Binance', group: 'SOCIAL', keywords: ['binance', 'binancecoin', 'bnb', 'binance-us'], officialDomains: ['binance.com', 'binance.us'] },
    { brand: 'OKX', group: 'SOCIAL', keywords: ['okx', 'okex', 'ok x'], officialDomains: ['okx.com'] },
    { brand: 'Bybit', group: 'SOCIAL', keywords: ['bybit', 'by bit'], officialDomains: ['bybit.com'] },
    { brand: 'Coinbase', group: 'SOCIAL', keywords: ['coinbase', 'coin base'], officialDomains: ['coinbase.com'] },
    { brand: 'Gate.io', group: 'SOCIAL', keywords: ['gateio', 'gate io'], officialDomains: ['gate.io'] },
    { brand: 'Bitget', group: 'SOCIAL', keywords: ['bitget', 'bit get'], officialDomains: ['bitget.com'] }
  ]
};
